const hotels = [
  {
    id: "1",
    name: "Oceanview Paradise",
    location: "Miami, Florida",
    price: "198,000",
    rating: "4.6",
    description:
      "A luxurious beachside retreat with stunning ocean views and world-class amenities.",
    longAddress: "123 Ocean Drive, Miami Beach, Florida, USA",
    facilities: [
      "pool",
      "spa",
      "wifi",
      "gym",
      "beach",
      "restaurant",
      "bar",
      "parking",
    ],
    reviews: [
      {
        name: "Emily Carter",
        comment: "Absolutely stunning and relaxing!",
        rating: 4.9,
      },
      {
        name: "John Doe",
        comment: "Beautiful location but the service was a bit slow.",
        rating: 4.2,
      },
      {
        user: "Chris Brown",
        comment: "Loved the mulled wine by the fireplace.",
        rating: "4.8",
      },
      {
        user: "Lisa Harper",
        comment: "The ski instructors were top-notch.",
        rating: "5",
      },
      {
        user: "Jack Morgan",
        comment: "Beautiful views and amazing facilities.",
        rating: "4.7",
      },
      {
        user: "Alex Rivera",
        comment: "The private beach was a dream come true.",
        rating: "5",
      },
      {
        user: "Nina Patel",
        comment: "Amazing food and perfect sunsets.",
        rating: "4.9",
      },
      {
        user: "Liam Carter",
        comment: "A little pricey, but worth every penny.",
        rating: "4.8",
      },
      {
        user: "Ella Fitzgerald",
        comment: "Best snorkeling experience ever.",
        rating: "5",
      },
      {
        user: "Ryan Adams",
        comment: "The staff were very accommodating.",
        rating: "4.7",
      },
    ],
    images: [
      require("../../assets/images/image1.jpg"),
      require("../../assets/images/image2.jpg"),
      require("../../assets/images/image12.jpg"),
      require("../../assets/images/image14.jpg"),
      require("../../assets/images/image5.jpg"),
      require("../../assets/images/image18.jpg"),
    ],
  },
  {
    id: "2",
    name: "Mountain Escape",
    location: "Aspen, Colorado",
    price: "300,000",
    rating: "4.7",
    description:
      "Cozy cabins nestled in the heart of the mountains, perfect for skiing enthusiasts.",
    longAddress: "45 Aspen Way, Aspen, Colorado, USA",
    facilities: [
      "ski",
      "breakfast",
      "mountain view",
      "hot tub",
      "fireplace",
      "bar",
      "wifi",
    ],
    reviews: [
      { name: "Sarah Lee", rating: 5, comment: "Best skiing experience ever!" },
      {
        name: "Mike Brown",
        comment: "Loved the hot tub after a day on the slopes.",
        rating: 4.5,
      },
      {
        user: "Ben Carter",
        comment: "Great ski slopes and cozy fireplaces.",
        rating: "5",
      },
      {
        user: "Emily Wong",
        comment: "A winter paradise with excellent staff.",
        rating: "4.9",
      },
      {
        user: "Emma Stone",
        comment: "Perfect for business trips.",
        rating: "4.5",
      },
      { user: "Harry Brown", comment: "Loved the rooftop bar.", rating: "4.7" },
      {
        user: "Sophia Li",
        comment: "The room design was modern and elegant.",
        rating: "4.6",
      },
    ],
    images: [
      require("../../assets/images/image8.jpg"),
      require("../../assets/images/image6.jpg"),
      require("../../assets/images/image7.jpg"),
      require("../../assets/images/image22.jpg"),
      require("../../assets/images/image20.jpg"),
      require("../../assets/images/image1.jpg"),
    ],
  },
  {
    id: "3",
    name: "City Lights Hotel",
    location: "New York, NY",
    price: "182,000",
    rating: "4.2",
    description:
      "A modern hotel in the heart of the city, with breathtaking views of the skyline.",
    longAddress: "99 Main Street, Manhattan, New York, NY, USA",
    facilities: [
      "wifi",
      "city view",
      "bar",
      "meeting",
      "gym",
      "parking",
      "spa",
    ],
    reviews: [
      {
        name: "David Johnson",
        rating: 4.5,
        comment: "Great location for exploring NYC!",
      },
      {
        name: "Anna White",
        rating: 4,
        comment: "Rooms were clean and spacious.",
      },
      {
        user: "David Clarke",
        comment: "The most luxurious stay I’ve ever had.",
        rating: "5",
      },
      {
        user: "Samantha Yates",
        comment: "The poolside service was excellent.",
        rating: "4.9",
      },
      { user: "Oliver King", comment: "A must-visit in Dubai.", rating: "5" },
      {
        user: "Chloe Parker",
        comment: "Stunning views and exceptional rooms.",
        rating: "4.8",
      },
      {
        user: "Ethan Lopez",
        comment: "Loved the Arabic-themed dining options.",
        rating: "5",
      },
      {
        user: "James Hill",
        comment: "So peaceful, a real escape from the city.",
        rating: "4.7",
      },
      {
        user: "Amelia Ross",
        comment: "The spa treatments were incredible.",
        rating: "4.8",
      },
      {
        user: "Ella Mitchell",
        comment: "Perfect for yoga and meditation.",
        rating: "4.6",
      },
      {
        user: "Leo Harris",
        comment: "The staff were incredibly friendly.",
        rating: "4.7",
      },
      {
        user: "Lily Howard",
        comment: "A great place to relax and recharge.",
        rating: "4.8",
      },
    ],
    images: [
      require("../../assets/images/image3.jpg"),
      require("../../assets/images/image4.jpg"),
      require("../../assets/images/image10.jpg"),
      require("../../assets/images/image16.jpg"),
      require("../../assets/images/image15.jpg"),
      require("../../assets/images/image23.jpg"),
      require("../../assets/images/image17.jpg"),
    ],
  },
  {
    id: "4",
    name: "Desert Oasis",
    location: "Phoenix, Arizona",
    price: "90,000",
    rating: "4.3",
    description:
      "Experience serenity in the desert with our luxurious pool and spa services.",
    longAddress: "123 Sun Road, Phoenix, Arizona, USA",
    facilities: [
      "pool",
      "parking",
      "spa",
      "pet",
      "beach",
      "restaurant",
      "bar",
      "wifi",
    ],
    reviews: [
      { name: "Michael Adams", rating: 4.2, comment: "Loved the tranquility!" },
      { name: "Lucy Gray", rating: 4.5, comment: "The spa was incredible!" },
      {
        user: "James Hill",
        comment: "So peaceful, a real escape from the city.",
        rating: "4.7",
      },
      {
        user: "Amelia Ross",
        comment: "The spa treatments were incredible.",
        rating: "4.8",
      },
      {
        user: "Ella Mitchell",
        comment: "Perfect for yoga and meditation.",
        rating: "4.6",
      },
      {
        user: "Leo Harris",
        comment: "The staff were incredibly friendly.",
        rating: "4.7",
      },
      {
        user: "Lily Howard",
        comment: "A great place to relax and recharge.",
        rating: "4.8",
      },
      {
        user: "Sophia Bennett",
        comment: "Perfect location for exploring NYC.",
        rating: "5",
      },
      {
        user: "Mason Carter",
        comment: "The rooftop bar had amazing views.",
        rating: "4.9",
      },
      {
        user: "Emma Kelly",
        comment: "Rooms were spacious and modern.",
        rating: "4.8",
      },
      {
        user: "Liam Taylor",
        comment: "Great value for such a central location.",
        rating: "4.7",
      },
      {
        user: "Olivia White",
        comment: "The breakfast buffet was excellent.",
        rating: "5",
      },
    ],
    images: [
      require("../../assets/images/image4.jpg"),
      require("../../assets/images/image5.jpg"),
      require("../../assets/images/image7.jpg"),
      require("../../assets/images/image18.jpg"),
      require("../../assets/images/image23.jpg"),
      require("../../assets/images/image24.jpg"),
      require("../../assets/images/image3.jpg"),
    ],
  },
  {
    id: "5",
    name: "Lakefront Lodge",
    location: "Geneva, Switzerland",
    price: "250,000",
    rating: "4.9",
    description:
      "Escape to a picturesque lodge by the lake with stunning water views.",
    longAddress: "456 Lakefront Avenue, Geneva, Switzerland",
    facilities: [
      "lake view",
      "Restaurant",
      "boat",
      "breakfast",
      "wifi",
      "parking",
      "spa",
      "pet",
    ],
    reviews: [
      {
        name: "Sophia Martin",
        rating: 5,
        comment: "The lake view was breathtaking!",
      },
      {
        name: "Jake Green",
        rating: 4.8,
        comment: "Fantastic place to relax and unwind.",
      },
      {
        user: "Emma Hill",
        comment: "Best ski resort I’ve ever stayed at.",
        rating: "5",
      },
      {
        user: "William Scott",
        comment: "The food was incredible.",
        rating: "4.8",
      },
      {
        user: "James Brown",
        comment: "A luxurious alpine experience.",
        rating: "4.9",
      },
      {
        user: "Ava Harris",
        comment: "The spa was perfect after a long day of skiing.",
        rating: "5",
      },
      {
        user: "Oliver Taylor",
        comment: "Beautiful and tranquil.",
        rating: "4.8",
      },
      {
        user: "Leo Martinez",
        comment: "Great cocktails by the beach.",
        rating: "4.5",
      },
      {
        user: "Sophia Lopez",
        comment: "The bungalows were so charming.",
        rating: "4.4",
      },
      {
        user: "Ava Young",
        comment: "Fantastic spot for water sports.",
        rating: "4.5",
      },
    ],
    images: [
      require("../../assets/images/image9.jpg"),
      require("../../assets/images/image8.jpg"),
      require("../../assets/images/image7.jpg"),
      require("../../assets/images/image22.jpg"),
      require("../../assets/images/image16.jpg"),
      require("../../assets/images/image14.jpg"),
      require("../../assets/images/image17.jpg"),
    ],
  },
  {
    id: "6",
    name: "Jungle Retreat",
    location: "Bali, Indonesia",
    price: "110,000",
    rating: "4.4",
    description:
      "Immerse yourself in nature with our eco-friendly resort surrounded by greenery.",
    longAddress: "789 Jungle Road, Bali, Indonesia",
    facilities: [
      "parking",
      "yoga",
      "hot tub",
      "nature",
      "spa",
      "wifi",
      "pool",
      "restaurant",
      "bar",
      " mountain view",
      "breakfast",
    ],
    reviews: [
      {
        name: "Eva Brown",
        rating: 4.5,
        comment: "A peaceful escape into nature!",
      },
      {
        name: "Tom Wilson",
        rating: 4.3,
        comment: "The yoga classes were amazing.",
      },
      {
        user: "Emma Hill",
        comment: "Best ski resort I’ve ever stayed at.",
        rating: "5",
      },
      {
        user: "William Scott",
        comment: "The food was incredible.",
        rating: "4.8",
      },
      {
        user: "James Brown",
        comment: "A luxurious alpine experience.",
        rating: "4.9",
      },
      {
        user: "Ava Harris",
        comment: "The spa was perfect after a long day of skiing.",
        rating: "5",
      },
      {
        user: "Oliver Taylor",
        comment: "Beautiful and tranquil.",
        rating: "4.8",
      },
      {
        user: "Ella Moore",
        comment: "Loved the beachfront yoga classes.",
        rating: "4.6",
      },
      {
        user: "Mason Allen",
        comment: "Very relaxing atmosphere.",
        rating: "4.5",
      },
      {
        user: "Jack Williams",
        comment: "Amazing views from every room.",
        rating: "5",
      },
      {
        user: "Luna Collins",
        comment: "The fireplace was perfect for chilly evenings.",
        rating: "4.8",
      },
    ],
    images: [
      require("../../assets/images/image17.jpg"),
      require("../../assets/images/image5.jpg"),
      require("../../assets/images/image23.jpg"),
      require("../../assets/images/image7.jpg"),
      require("../../assets/images/image2.jpg"),
      require("../../assets/images/image14.jpg"),
      require("../../assets/images/image15.jpg"),
      require("../../assets/images/image12.jpg"),
    ],
  },
  {
    id: "7",
    name: "Island Dreams Resort",
    location: "Maldives",
    price: "290,000",
    rating: "4.8",
    description:
      "Luxury villas above crystal-clear waters, offering the ultimate island escape.",
    longAddress: "101 Paradise Beach, Maldives",
    facilities: [
      "bar",
      "pool",
      "snorkeling",
      "all-inclusive",
      "spa",
      "wifi",
      "beach",
      "restaurant",
      "fireplace",
    ],
    reviews: [
      { name: "Laura Smith", rating: 5, comment: "Pure paradise on earth!" },
      {
        name: "Chris Miller",
        rating: 4.9,
        comment: "The overwater villas were unforgettable.",
      },
      {
        user: "Sophia Bennett",
        comment: "Perfect location for exploring NYC.",
        rating: "5",
      },
      {
        user: "Mason Carter",
        comment: "The rooftop bar had amazing views.",
        rating: "4.9",
      },
      {
        user: "Emma Kelly",
        comment: "Rooms were spacious and modern.",
        rating: "4.8",
      },
      {
        user: "Liam Taylor",
        comment: "Great value for such a central location.",
        rating: "4.7",
      },
      {
        user: "Olivia White",
        comment: "The breakfast buffet was excellent.",
        rating: "5",
      },
    ],
    images: [
      require("../../assets/images/image8.jpg"),
      require("../../assets/images/image7.jpg"),
      require("../../assets/images/image5.jpg"),
    ],
  },
  {
    id: "8",
    name: "Countryside Inn",
    location: "Tuscany, Italy",
    price: "120,000",
    rating: "4.1",
    description:
      "Charming countryside inn with breathtaking vineyard views and Italian cuisine.",
    longAddress: "22 Vineyard Lane, Tuscany, Italy",
    facilities: [
      "pool",
      "breakfast",
      "fireplace",
      "cycling",
      "wifi",
      "restaurant",
      "bar",
      "parking",
    ],
    reviews: [
      { name: "Diana Evans", rating: 4.2, comment: "Perfect for wine lovers!" },
      {
        name: "George White",
        rating: 4.1,
        comment: "Beautiful and peaceful location.",
      },
      {
        user: "Amelia Ross",
        comment: "The spa treatments were incredible.",
        rating: "4.8",
      },
      {
        user: "Ella Mitchell",
        comment: "Perfect for yoga and meditation.",
        rating: "4.6",
      },
    ],
    images: [
      require("../../assets/images/image14.jpg"),
      require("../../assets/images/image9.jpg"),
      require("../../assets/images/image17.jpg"),
      require("../../assets/images/image1.jpg"),
      require("../../assets/images/image23.jpg"),
    ],
  },
  {
    id: "9",
    name: "Urban Comfort",
    location: "London, UK",
    price: "150,000",
    rating: "4.3",
    description:
      "A modern, urban hotel with sleek designs and easy access to city attractions.",
    longAddress: "11 Comfort Street, London, UK",
    facilities: ["wifi", "city view", "bar", "meeting", "gym"],
    reviews: [
      {
        name: "Olivia Brown",
        rating: 4.3,
        comment: "Convenient location and comfortable stay.",
      },
      { name: "Ethan Lee", rating: 4.5, comment: "Loved the modern design!" },
      {
        user: "David Clarke",
        comment: "The most luxurious stay I’ve ever had.",
        rating: "5",
      },
      {
        user: "Samantha Yates",
        comment: "The poolside service was excellent.",
        rating: "4.9",
      },
      { user: "Oliver King", comment: "A must-visit in Dubai.", rating: "5" },
      {
        user: "Chloe Parker",
        comment: "Stunning views and exceptional rooms.",
        rating: "4.8",
      },
      {
        user: "Ethan Lopez",
        comment: "Loved the Arabic-themed dining options.",
        rating: "5",
      },
    ],
    images: [
      require("../../assets/images/image19.jpg"),
      require("../../assets/images/image20.jpg"),
      require("../../assets/images/image3.jpg"),
      require("../../assets/images/image5.jpg"),
      require("../../assets/images/image18.jpg"),
      require("../../assets/images/image15.jpg"),
    ],
  },
  {
    id: "10",
    name: "Coastal Bliss",
    location: "Sydney, Australia",
    price: "220,000",
    rating: "4.8",
    description:
      "Beachfront luxury with panoramic ocean views and exclusive amenities.",
    longAddress: "33 Beachside Avenue, Sydney, Australia",
    facilities: [
      "beach",
      "pool",
      "spa",
      "wifi",
      "meeting",
      "gym",
      "parking",
      "restaurant",
      "bar",
    ],
    reviews: [
      { name: "Alice Turner", rating: 5, comment: "The view was spectacular!" },
      {
        name: "Jack Harris",
        rating: 4.7,
        comment: "Great for a romantic getaway.",
      },
      {
        user: "Nina Patel",
        comment: "Amazing food and perfect sunsets.",
        rating: "4.9",
      },
      {
        user: "Liam Carter",
        comment: "A little pricey, but worth every penny.",
        rating: "4.8",
      },
      {
        user: "Ella Fitzgerald",
        comment: "Best snorkeling experience ever.",
        rating: "5",
      },
      {
        user: "Emma Stone",
        comment: "Perfect for business trips.",
        rating: "4.5",
      },
      { user: "Harry Brown", comment: "Loved the rooftop bar.", rating: "4.7" },
      {
        user: "Sophia Li",
        comment: "The room design was modern and elegant.",
        rating: "4.6",
      },
      {
        user: "Ben Carter",
        comment: "Great ski slopes and cozy fireplaces.",
        rating: "5",
      },
      {
        user: "Emily Wong",
        comment: "A winter paradise with excellent staff.",
        rating: "4.9",
      },
      {
        user: "Chris Brown",
        comment: "Loved the mulled wine by the fireplace.",
        rating: "4.8",
      },
    ],
    images: [
      require("../../assets/images/image20.jpg"),
      require("../../assets/images/image15.jpg"),
      require("../../assets/images/image18.jpg"),
      require("../../assets/images/image14.jpg"),
      require("../../assets/images/image3.jpg"),
      require("../../assets/images/image2.jpg"),
      require("../../assets/images/image1.jpg"),
      require("../../assets/images/image16.jpg"),
    ],
  },
  {
    id: "11",
    name: "Coastal Retreat",
    location: "Santorini, Greece",
    longAddress: "123 Seaside Blvd, Santorini, Greece, 84700",
    price: "75,000",
    rating: "4.7",
    description:
      "A serene coastal retreat offering breathtaking ocean views and luxurious accommodations.",
    facilities: ["wifi", "restaurant", "pool", "spa", "gym", "beach", "bar"],
    images: [
      require("../../assets/images/image21.jpg"),
      require("../../assets/images/image19.jpg"),
      require("../../assets/images/image13.jpg"),
      require("../../assets/images/image4.jpg"),
      require("../../assets/images/image7.jpg"),
      require("../../assets/images/image9.jpg"),
      require("../../assets/images/image10.jpg"),
    ],
    reviews: [
      {
        user: "Anna Michaels",
        comment: "Loved the infinity pool and the view was stunning!",
        rating: "5",
      },
      {
        user: "Tom Greene",
        comment: "Amazing food and great service.",
        rating: "4.8",
      },
      {
        user: "Sophia Lee",
        comment: "Perfect for a romantic getaway.",
        rating: "5",
      },
      {
        user: "John Doe",
        comment: "The gym was well-equipped, and the staff were very polite.",
        rating: "4.6",
      },
      {
        user: "Maria Alvarez",
        comment: "The spa treatments were heavenly!",
        rating: "5",
      },
      {
        user: "David Clarke",
        comment: "The most luxurious stay I’ve ever had.",
        rating: "5",
      },
      {
        user: "Samantha Yates",
        comment: "The poolside service was excellent.",
        rating: "4.9",
      },
      { user: "Oliver King", comment: "A must-visit in Dubai.", rating: "5" },
      {
        user: "Chloe Parker",
        comment: "Stunning views and exceptional rooms.",
        rating: "4.8",
      },
      {
        user: "Ethan Lopez",
        comment: "Loved the Arabic-themed dining options.",
        rating: "5",
      },
    ],
  },
  {
    id: "12",
    name: "The pheels",
    location: "Ajah, Lagos",
    longAddress: "45 Alpine St, Ajah, Lagos, 81611",
    price: "120,000",
    rating: "4.9",
    description:
      "Nestled in the heart of the mountains, this haven offers both adventure and relaxation.",
    facilities: ["wifi", "restaurant", "bar", "ski", "fireplace"],
    images: [
      require("../../assets/images/image5.jpg"),
      require("../../assets/images/image6.jpg"),
      require("../../assets/images/image7.jpg"),
      require("../../assets/images/image18.jpg"),
      require("../../assets/images/image17.jpg"),
      require("../../assets/images/image11.jpg"),
    ],
    reviews: [
      {
        user: "Ben Carter",
        comment: "Great ski slopes and cozy fireplaces.",
        rating: "5",
      },
      {
        user: "Emily Wong",
        comment: "A winter paradise with excellent staff.",
        rating: "4.9",
      },
      {
        user: "Chris Brown",
        comment: "Loved the mulled wine by the fireplace.",
        rating: "4.8",
      },
      {
        user: "Lisa Harper",
        comment: "The ski instructors were top-notch.",
        rating: "5",
      },
      {
        user: "Jack Morgan",
        comment: "Beautiful views and amazing facilities.",
        rating: "4.7",
      },
      {
        user: "James Hill",
        comment: "So peaceful, a real escape from the city.",
        rating: "4.7",
      },
      {
        user: "Amelia Ross",
        comment: "The spa treatments were incredible.",
        rating: "4.8",
      },
      {
        user: "Ella Mitchell",
        comment: "Perfect for yoga and meditation.",
        rating: "4.6",
      },
      {
        user: "Leo Harris",
        comment: "The staff were incredibly friendly.",
        rating: "4.7",
      },
      {
        user: "Lily Howard",
        comment: "A great place to relax and recharge.",
        rating: "4.8",
      },
      {
        user: "Sophia Bennett",
        comment: "Perfect location for exploring NYC.",
        rating: "5",
      },
      {
        user: "Mason Carter",
        comment: "The rooftop bar had amazing views.",
        rating: "4.9",
      },
      {
        user: "Emma Kelly",
        comment: "Rooms were spacious and modern.",
        rating: "4.8",
      },
      {
        user: "Liam Taylor",
        comment: "Great value for such a central location.",
        rating: "4.7",
      },
      {
        user: "Olivia White",
        comment: "The breakfast buffet was excellent.",
        rating: "5",
      },
    ],
  },
  {
    id: "13",
    name: "Estabeez",
    location: "Ikoyi, Lagos",
    longAddress: "56 Akihabara St, Ikoyi, Lagos, 101-002",
    price: "95,000",
    rating: "4.6",
    description:
      "Experience the bustling city life with a blend of modern luxury.",
    facilities: [
      "wifi",
      "restaurant",
      "bar",
      "gym",
      "parking",
      "meeting",
      "breakfast",
      "pool",
    ],
    images: [
      require("../../assets/images/image10.jpg"),
      require("../../assets/images/image2.jpg"),
      require("../../assets/images/image23.jpg"),
      require("../../assets/images/image3.jpg"),
      require("../../assets/images/image17.jpg"),
      require("../../assets/images/image18.jpg"),
    ],
    reviews: [
      {
        user: "Alice Kim",
        comment: "Loved the sushi at the in-house restaurant!",
        rating: "4.8",
      },
      {
        user: "Mike Jacobs",
        comment: "Central location and great facilities.",
        rating: "4.6",
      },
      {
        user: "Emma Stone",
        comment: "Perfect for business trips.",
        rating: "4.5",
      },
      { user: "Harry Brown", comment: "Loved the rooftop bar.", rating: "4.7" },
      {
        user: "Sophia Li",
        comment: "The room design was modern and elegant.",
        rating: "4.6",
      },
    ],
  },
  {
    id: "14",
    name: "Saragoza",
    location: "Pukhet, Tailand",
    longAddress: "12 Lagoon Rd, Pukhet, Tailand, 20252",
    price: "180,000",
    rating: "4.8",
    description: "Relax in a private villa surrounded by crystal-clear waters.",
    facilities: [
      "wifi",
      "pool",
      "bar",
      "spa",
      "beach",
      "restaurant",
      "parking",
    ],
    images: [
      require("../../assets/images/image14.jpg"),
      require("../../assets/images/image5.jpg"),
      require("../../assets/images/image6.jpg"),
      require("../../assets/images/image17.jpg"),
      require("../../assets/images/image18.jpg"),
      require("../../assets/images/image20.jpg"),
      require("../../assets/images/image1.jpg"),
      require("../../assets/images/image9.jpg"),
    ],
    reviews: [
      {
        user: "Alex Rivera",
        comment: "The private beach was a dream come true.",
        rating: "5",
      },
      {
        user: "Nina Patel",
        comment: "Amazing food and perfect sunsets.",
        rating: "4.9",
      },
      {
        user: "Liam Carter",
        comment: "A little pricey, but worth every penny.",
        rating: "4.8",
      },
      {
        user: "Ella Fitzgerald",
        comment: "Best snorkeling experience ever.",
        rating: "5",
      },
      {
        user: "Ryan Adams",
        comment: "The staff were very accommodating.",
        rating: "4.7",
      },
      {
        user: "Leo Martinez",
        comment: "Great cocktails by the beach.",
        rating: "4.5",
      },
      {
        user: "Sophia Lopez",
        comment: "The bungalows were so charming.",
        rating: "4.4",
      },
      {
        user: "Ava Young",
        comment: "Fantastic spot for water sports.",
        rating: "4.5",
      },
      {
        user: "Ella Moore",
        comment: "Loved the beachfront yoga classes.",
        rating: "4.6",
      },
      {
        user: "Mason Allen",
        comment: "Very relaxing atmosphere.",
        rating: "4.5",
      },
    ],
  },
  {
    id: "15",
    name: "Golden Sands Resort",
    location: "Dubai, UAE",
    longAddress: "33 Sheikh Zayed Rd, Dubai, UAE, 00000",
    price: "205,000",
    rating: "4.9",
    description:
      "A luxurious desert oasis with stunning architecture and top-tier services.",
    facilities: ["wifi", "restaurant", "pool", "spa", "gym"],
    images: [
      require("../../assets/images/image19.jpg"),
      require("../../assets/images/image20.jpg"),
      require("../../assets/images/image22.jpg"),
      require("../../assets/images/image2.jpg"),
      require("../../assets/images/image3.jpg"),
      require("../../assets/images/image10.jpg"),
    ],
    reviews: [
      {
        user: "David Clarke",
        comment: "The most luxurious stay I’ve ever had.",
        rating: "5",
      },
      {
        user: "Samantha Yates",
        comment: "The poolside service was excellent.",
        rating: "4.9",
      },
      { user: "Oliver King", comment: "A must-visit in Dubai.", rating: "5" },
      {
        user: "Chloe Parker",
        comment: "Stunning views and exceptional rooms.",
        rating: "4.8",
      },
      {
        user: "Ethan Lopez",
        comment: "Loved the Arabic-themed dining options.",
        rating: "5",
      },
      {
        user: "Alex Rivera",
        comment: "The private beach was a dream come true.",
        rating: "5",
      },
      {
        user: "Nina Patel",
        comment: "Amazing food and perfect sunsets.",
        rating: "4.9",
      },
      {
        user: "Liam Carter",
        comment: "A little pricey, but worth every penny.",
        rating: "4.8",
      },
      {
        user: "Ella Fitzgerald",
        comment: "Best snorkeling experience ever.",
        rating: "5",
      },
      {
        user: "Ryan Adams",
        comment: "The staff were very accommodating.",
        rating: "4.7",
      },
    ],
  },
  {
    id: "16",
    name: "Rainforest Retreat",
    location: "Bali, Indonesia",
    longAddress: "45 Jungle Path, Ubud, Bali, 80571",
    price: "70,000",
    rating: "4.6",
    description:
      "Reconnect with nature in this peaceful retreat surrounded by lush greenery.",
    facilities: [
      "wifi",
      "restaurant",
      "bar",
      "pool",
      "spa",
      "yoga",
      "nature",
      "parking",
    ],
    images: [
      require("../../assets/images/image1.jpg"),
      require("../../assets/images/image2.jpg"),
      require("../../assets/images/image13.jpg"),
      require("../../assets/images/image24.jpg"),
      require("../../assets/images/image8.jpg"),
      require("../../assets/images/image12.jpg"),
      require("../../assets/images/image11.jpg"),
    ],
    reviews: [
      {
        user: "James Hill",
        comment: "So peaceful, a real escape from the city.",
        rating: "4.7",
      },
      {
        user: "Amelia Ross",
        comment: "The spa treatments were incredible.",
        rating: "4.8",
      },
      {
        user: "Ella Mitchell",
        comment: "Perfect for yoga and meditation.",
        rating: "4.6",
      },
      {
        user: "Leo Harris",
        comment: "The staff were incredibly friendly.",
        rating: "4.7",
      },
      {
        user: "Lily Howard",
        comment: "A great place to relax and recharge.",
        rating: "4.8",
      },
      {
        user: "Alex Rivera",
        comment: "The private beach was a dream come true.",
        rating: "5",
      },
      {
        user: "Nina Patel",
        comment: "Amazing food and perfect sunsets.",
        rating: "4.9",
      },
      {
        user: "Liam Carter",
        comment: "A little pricey, but worth every penny.",
        rating: "4.8",
      },
      {
        user: "Ella Fitzgerald",
        comment: "Best snorkeling experience ever.",
        rating: "5",
      },
      {
        user: "Ryan Adams",
        comment: "The staff were very accommodating.",
        rating: "4.7",
      },
      {
        user: "Alice Kim",
        comment: "Loved the sushi at the in-house restaurant!",
        rating: "4.8",
      },
      {
        user: "Mike Jacobs",
        comment: "Central location and great facilities.",
        rating: "4.6",
      },
      {
        user: "Emma Stone",
        comment: "Perfect for business trips.",
        rating: "4.5",
      },
      { user: "Harry Brown", comment: "Loved the rooftop bar.", rating: "4.7" },
      {
        user: "Sophia Li",
        comment: "The room design was modern and elegant.",
        rating: "4.6",
      },
    ],
  },
  {
    id: "17",
    name: "Cityscape Hotel",
    location: "New York, USA",
    longAddress: "100 Manhattan Ave, New York, NY, 10001",
    price: "150,000",
    rating: "4.8",
    description: "A modern city escape located in the heart of Manhattan.",
    facilities: ["wifi", "restaurant", "gym", "bar", "parking", "city view"],
    images: [
      require("../../assets/images/image5.jpg"),
      require("../../assets/images/image2.jpg"),
      require("../../assets/images/image17.jpg"),
      require("../../assets/images/image18.jpg"),
      require("../../assets/images/image1.jpg"),
      require("../../assets/images/image3.jpg"),
      require("../../assets/images/image20.jpg"),
    ],
    reviews: [
      {
        user: "Sophia Bennett",
        comment: "Perfect location for exploring NYC.",
        rating: "5",
      },
      {
        user: "Mason Carter",
        comment: "The rooftop bar had amazing views.",
        rating: "4.9",
      },
      {
        user: "Emma Kelly",
        comment: "Rooms were spacious and modern.",
        rating: "4.8",
      },
      {
        user: "Liam Taylor",
        comment: "Great value for such a central location.",
        rating: "4.7",
      },
      {
        user: "Olivia White",
        comment: "The breakfast buffet was excellent.",
        rating: "5",
      },
    ],
  },
  {
    id: "18",
    name: "Lakeview Lodge",
    location: "Queenstown, New Zealand",
    longAddress: "88 Scenic Rd, Queenstown, New Zealand, 9300",
    price: "112,000",
    rating: "4.7",
    description:
      "Enjoy breathtaking views of the lake and surrounding mountains.",
    facilities: [
      "wifi",
      "restaurant",
      "pool",
      "gym",
      "fireplace",
      "parking",
      "spa",
      "lake",
    ],
    images: [
      require("../../assets/images/image9.jpg"),
      require("../../assets/images/image13.jpg"),
      require("../../assets/images/image10.jpg"),
      require("../../assets/images/image2.jpg"),
      require("../../assets/images/image21.jpg"),
      require("../../assets/images/image20.jpg"),
      require("../../assets/images/image14.jpg"),
    ],
    reviews: [
      {
        user: "Alice Kim",
        comment: "Loved the sushi at the in-house restaurant!",
        rating: "4.8",
      },
      {
        user: "Mike Jacobs",
        comment: "Central location and great facilities.",
        rating: "4.6",
      },
      {
        user: "Emma Stone",
        comment: "Perfect for business trips.",
        rating: "4.5",
      },
      { user: "Harry Brown", comment: "Loved the rooftop bar.", rating: "4.7" },
      {
        user: "Sophia Li",
        comment: "The room design was modern and elegant.",
        rating: "4.6",
      },
      {
        user: "Jack Williams",
        comment: "Amazing views from every room.",
        rating: "5",
      },
      {
        user: "Luna Collins",
        comment: "The fireplace was perfect for chilly evenings.",
        rating: "4.8",
      },
      {
        user: "Ben Carter",
        comment: "Great ski slopes and cozy fireplaces.",
        rating: "5",
      },
      {
        user: "Emily Wong",
        comment: "A winter paradise with excellent staff.",
        rating: "4.9",
      },
      {
        user: "Oscar Davis",
        comment: "The staff went above and beyond.",
        rating: "4.7",
      },
      {
        user: "Mia Hall",
        comment: "Great location for skiing.",
        rating: "4.9",
      },
      {
        user: "Ella Wilson",
        comment: "Comfortable and cozy rooms.",
        rating: "4.6",
      },
    ],
  },
  {
    id: "19",
    name: "Beachside Bungalows",
    location: "Cancun, Mexico",
    longAddress: "22 Ocean Rd, Cancun, Mexico, 77500",
    price: "65,000",
    rating: "4.5",
    description: "Relax in beachfront bungalows with a laid-back vibe.",
    facilities: [
      "wifi",
      "bar",
      "pool",
      "beach",
      "restaurant",
      "spa",
      "parking",
    ],
    images: [
      require("../../assets/images/image13.jpg"),
      require("../../assets/images/image1.jpg"),
      require("../../assets/images/image5.jpg"),
      require("../../assets/images/image16.jpg"),
      require("../../assets/images/image14.jpg"),
      require("../../assets/images/image9.jpg"),
      require("../../assets/images/image10.jpg"),
    ],
    reviews: [
      {
        user: "Leo Martinez",
        comment: "Great cocktails by the beach.",
        rating: "4.5",
      },
      {
        user: "Sophia Lopez",
        comment: "The bungalows were so charming.",
        rating: "4.4",
      },
      {
        user: "Ava Young",
        comment: "Fantastic spot for water sports.",
        rating: "4.5",
      },
      {
        user: "Chris Brown",
        comment: "Loved the mulled wine by the fireplace.",
        rating: "4.8",
      },
      {
        user: "Lisa Harper",
        comment: "The ski instructors were top-notch.",
        rating: "5",
      },
      {
        user: "Jack Morgan",
        comment: "Beautiful views and amazing facilities.",
        rating: "4.7",
      },
      {
        user: "Mike Jacobs",
        comment: "Central location and great facilities.",
        rating: "4.6",
      },
      {
        user: "Emma Stone",
        comment: "Perfect for business trips.",
        rating: "4.5",
      },
      { user: "Harry Brown", comment: "Loved the rooftop bar.", rating: "4.7" },
      {
        user: "Ella Moore",
        comment: "Loved the beachfront yoga classes.",
        rating: "4.6",
      },
      {
        user: "Mason Allen",
        comment: "Very relaxing atmosphere.",
        rating: "4.5",
      },
    ],
  },
  {
    id: "20",
    name: "Winter Wonderland Resort",
    location: "Zermatt, Switzerland",
    longAddress: "1 Glacier Rd, Zermatt, Switzerland, 3920",
    price: "253,000",
    rating: "4.9",
    description:
      "Experience the magic of the Swiss Alps with world-class skiing.",
    facilities: [
      "wifi",
      "restaurant",
      "bar",
      "ski",
      "spa",
      "fireplace",
      "parking",
      "mountain view",
      "breakfast",
    ],
    images: [
      require("../../assets/images/image7.jpg"),
      require("../../assets/images/image8.jpg"),
      require("../../assets/images/image19.jpg"),
      require("../../assets/images/image10.jpg"),
      require("../../assets/images/image11.jpg"),
      require("../../assets/images/image22.jpg"),
      require("../../assets/images/image18.jpg"),
      require("../../assets/images/image1.jpg"),
    ],
    reviews: [
      {
        user: "Emma Hill",
        comment: "Best ski resort I’ve ever stayed at.",
        rating: "5",
      },
      {
        user: "William Scott",
        comment: "The food was incredible.",
        rating: "4.8",
      },
      {
        user: "Anna Michaels",
        comment: "Loved the infinity pool and the view was stunning!",
        rating: "5",
      },
      {
        user: "Tom Greene",
        comment: "Amazing food and great service.",
        rating: "4.8",
      },
      {
        user: "Sophia Lee",
        comment: "Perfect for a romantic getaway.",
        rating: "5",
      },
      {
        user: "John Doe",
        comment: "The gym was well-equipped, and the staff were very polite.",
        rating: "4.6",
      },
      {
        user: "James Brown",
        comment: "A luxurious alpine experience.",
        rating: "4.9",
      },
      {
        user: "Ava Harris",
        comment: "The spa was perfect after a long day of skiing.",
        rating: "5",
      },
      {
        user: "Oliver Taylor",
        comment: "Beautiful and tranquil.",
        rating: "4.8",
      },
    ],
  },
];

const slidesData = [
  {
    image: require("../../assets/images/image1.jpg"),
    textLines: [
      { text: "Last-minute", style: "sliderTextSemibold" },
      { text: "weekend", style: "sliderTextbold" },
      { text: "deals", style: "sliderText" },
    ],
  },
  {
    image: require("../../assets/images/image8.jpg"),
    textLines: [
      { text: "Get", style: "sliderTextSemibold" },
      { text: "10% OFF", style: "sliderTextbold" },
      { text: "on your first booking", style: "sliderText" },
    ],
  },
  {
    image: require("../../assets/images/image5.jpg"),
    textLines: [
      { text: "Planning", style: "sliderTextSemibold" },
      { text: "a new Escape?", style: "sliderTextbold" },
      { text: "Let's explore", style: "sliderText" },
    ],
  },
];

export { slidesData, hotels };
