const hotels = [
  {
    id: "1",
    name: "Oceanview Paradise",
    location: "Miami, Florida",
    price: "198,000",
    rating: "4.6",
    description:
      "A luxurious beachside retreat with stunning ocean views and world-class amenities.",
    longAddress: "123 Ocean Drive, Miami Beach, Florida, USA",
    facilities: [
      "pool",
      "spa",
      "wifi",
      "gym",
      "beach",
      "restaurant",
      "bar",
      "parking",
    ],
    reviews: [
      {
        user: "Emily Carter",
        comment: "Absolutely stunning and relaxing!",
        rating: 4.9,
        date: "May 4, 2023",
        avatar: require("../../assets/profiles/profile5.jpg"),
      },
      {
        user: "John Doe",
        comment: "Beautiful location but the service was a bit slow.",
        rating: 4.2,
        date: "Feb 15, 2023",
        avatar: require("../../assets/profiles/profile12.jpg"),
      },
      {
        user: "Chris Brown",
        comment: "Loved the mulled wine by the fireplace.",
        rating: 4.8,
        date: "Jun 8, 2023",
        avatar: require("../../assets/profiles/profile3.jpg"),
      },
      {
        user: "Lisa Harper",
        comment: "The ski instructors were top-notch.",
        rating: 5,
        date: "Jul 10, 2023",
        avatar: require("../../assets/profiles/profile8.jpg"),
      },
      {
        user: "Jack Morgan",
        comment: "Beautiful views and amazing facilities.",
        rating: 4.7,
        date: "Aug 18, 2023",
        avatar: require("../../assets/profiles/profile2.jpg"),
      },
      {
        user: "Alex Rivera",
        comment: "The private beach was a dream come true.",
        rating: 5,
        date: "Sep 5, 2023",
        avatar: require("../../assets/profiles/profile10.jpg"),
      },
      {
        user: "Nina Patel",
        comment: "Amazing food and perfect sunsets.",
        rating: 4.9,
        date: "Oct 3, 2023",
        avatar: require("../../assets/profiles/profile7.jpg"),
      },
      {
        user: "Liam Carter",
        comment: "A little pricey, but worth every penny.",
        rating: 4.8,
        date: "Nov 21, 2023",
        avatar: require("../../assets/profiles/profile4.jpg"),
      },
      {
        user: "Ella Fitzgerald",
        comment: "Best snorkeling experience ever.",
        rating: 5,
        date: "Dec 12, 2023",
        avatar: require("../../assets/profiles/profile11.jpg"),
      },
      {
        user: "Ryan Adams",
        comment: "The staff were very accommodating.",
        rating: 4.7,
        date: "Jan 19, 2024",
        avatar: require("../../assets/profiles/profile9.jpg"),
      },
    ],
    images: [
      require("../../assets/images/image1.jpg"),
      require("../../assets/images/image2.jpg"),
      require("../../assets/images/image12.jpg"),
      require("../../assets/images/image14.jpg"),
      require("../../assets/images/image5.jpg"),
      require("../../assets/images/image18.jpg"),
    ],
  },
  {
    id: "2",
    name: "Mountain Escape",
    location: "Aspen, Colorado",
    price: "300,000",
    rating: "4.7",
    description:
      "Cozy cabins nestled in the heart of the mountains, perfect for skiing enthusiasts.",
    longAddress: "45 Aspen Way, Aspen, Colorado, USA",
    facilities: [
      "ski",
      "breakfast",
      "mountain view",
      "hot tub",
      "fireplace",
      "bar",
      "wifi",
    ],
    reviews: [
      {
        user: "Sarah Lee",
        rating: 5,
        comment: "Best skiing experience ever!",
        date: "Feb 10, 2023",
        avatar: require("../../assets/profiles/profile6.jpg"),
      },
      {
        user: "Mike Brown",
        comment: "Loved the hot tub after a day on the slopes.",
        rating: 4.5,
        date: "Mar 12, 2023",
        avatar: require("../../assets/profiles/profile13.jpg"),
      },
      {
        user: "Ben Carter",
        comment: "Great ski slopes and cozy fireplaces.",
        rating: 5,
        date: "Apr 22, 2023",
        avatar: require("../../assets/profiles/profile8.jpg"),
      },
      {
        user: "Emily Wong",
        comment: "A winter paradise with excellent staff.",
        rating: 4.9,
        date: "May 5, 2023",
        avatar: require("../../assets/profiles/profile4.jpg"),
      },
      {
        user: "Emma Stone",
        comment: "Perfect for business trips.",
        rating: 4.5,
        date: "Jun 18, 2023",
        avatar: require("../../assets/profiles/profile7.jpg"),
      },
      {
        user: "Harry Brown",
        comment: "Loved the rooftop bar.",
        rating: 4.7,
        date: "Jul 30, 2023",
        avatar: require("../../assets/profiles/profile2.jpg"),
      },
      {
        user: "Sophia Li",
        comment: "The room design was modern and elegant.",
        rating: 4.6,
        date: "Aug 14, 2023",
        avatar: require("../../assets/profiles/profile9.jpg"),
      },
    ],
    images: [
      require("../../assets/images/image8.jpg"),
      require("../../assets/images/image6.jpg"),
      require("../../assets/images/image7.jpg"),
      require("../../assets/images/image22.jpg"),
      require("../../assets/images/image20.jpg"),
      require("../../assets/images/image1.jpg"),
    ],
  },
  {
    id: "3",
    name: "City Lights Hotel",
    location: "New York, NY",
    price: "182,000",
    rating: "4.2",
    description:
      "A modern hotel in the heart of the city, with breathtaking views of the skyline.",
    longAddress: "99 Main Street, Manhattan, New York, NY, USA",
    facilities: [
      "wifi",
      "city view",
      "bar",
      "meeting",
      "gym",
      "parking",
      "spa",
    ],
    reviews: [
      {
        user: "David Johnson",
        rating: 4.5,
        comment: "Great location for exploring NYC!",
        date: "Jan 15, 2023",
        avatar: require("../../assets/profiles/profile1.jpg"),
      },
      {
        user: "Anna White",
        rating: 4,
        comment: "Rooms were clean and spacious.",
        date: "Feb 20, 2023",
        avatar: require("../../assets/profiles/profile3.jpg"),
      },
      {
        user: "David Clarke",
        comment: "The most luxurious stay I’ve ever had.",
        rating: 5,
        date: "Mar 17, 2023",
        avatar: require("../../assets/profiles/profile5.jpg"),
      },
      {
        user: "Samantha Yates",
        comment: "The poolside service was excellent.",
        rating: 4.9,
        date: "Apr 22, 2023",
        avatar: require("../../assets/profiles/profile2.jpg"),
      },
      {
        user: "Oliver King",
        comment: "A must-visit in Dubai.",
        rating: 5,
        date: "May 30, 2023",
        avatar: require("../../assets/profiles/profile8.jpg"),
      },
      {
        user: "Chloe Parker",
        comment: "Stunning views and exceptional rooms.",
        rating: 4.8,
        date: "Jun 12, 2023",
        avatar: require("../../assets/profiles/profile6.jpg"),
      },
      {
        user: "Ethan Lopez",
        comment: "Loved the Arabic-themed dining options.",
        rating: 5,
        date: "Jul 7, 2023",
        avatar: require("../../assets/profiles/profile9.jpg"),
      },
      {
        user: "James Hill",
        comment: "So peaceful, a real escape from the city.",
        rating: 4.7,
        date: "Aug 20, 2023",
        avatar: require("../../assets/profiles/profile4.jpg"),
      },
      {
        user: "Amelia Ross",
        comment: "The spa treatments were incredible.",
        rating: 4.8,
        date: "Sep 10, 2023",
        avatar: require("../../assets/profiles/profile11.jpg"),
      },
      {
        user: "Ella Mitchell",
        comment: "Perfect for yoga and meditation.",
        rating: 4.6,
        date: "Oct 3, 2023",
        avatar: require("../../assets/profiles/profile7.jpg"),
      },
      {
        user: "Leo Harris",
        comment: "The staff were incredibly friendly.",
        rating: 4.7,
        date: "Nov 12, 2023",
        avatar: require("../../assets/profiles/profile10.jpg"),
      },
      {
        user: "Lily Howard",
        comment: "A great place to relax and recharge.",
        rating: 4.8,
        date: "Dec 9, 2023",
        avatar: require("../../assets/profiles/profile12.jpg"),
      },
    ],
    images: [
      require("../../assets/images/image3.jpg"),
      require("../../assets/images/image4.jpg"),
      require("../../assets/images/image10.jpg"),
      require("../../assets/images/image16.jpg"),
      require("../../assets/images/image15.jpg"),
      require("../../assets/images/image23.jpg"),
      require("../../assets/images/image17.jpg"),
    ],
  },
  {
    id: "4",
    name: "Desert Oasis",
    location: "Phoenix, Arizona",
    price: "90,000",
    rating: "4.3",
    description:
      "Experience serenity in the desert with our luxurious pool and spa services.",
    longAddress: "123 Sun Road, Phoenix, Arizona, USA",
    facilities: [
      "pool",
      "parking",
      "spa",
      "pet",
      "beach",
      "restaurant",
      "bar",
      "wifi",
    ],
    reviews: [
      {
        user: "Michael Adams",
        rating: 4.2,
        comment: "Loved the tranquility!",
        date: "Jan 10, 2023",
        avatar: require("../../assets/profiles/profile4.jpg"),
      },
      {
        user: "Lucy Gray",
        rating: 4.5,
        comment: "The spa was incredible!",
        date: "Feb 5, 2023",
        avatar: require("../../assets/profiles/profile6.jpg"),
      },
      {
        user: "James Hill",
        comment: "So peaceful, a real escape from the city.",
        rating: 4.7,
        date: "Mar 14, 2023",
        avatar: require("../../assets/profiles/profile7.jpg"),
      },
      {
        user: "Amelia Ross",
        comment: "The spa treatments were incredible.",
        rating: 4.8,
        date: "Apr 2, 2023",
        avatar: require("../../assets/profiles/profile9.jpg"),
      },
      {
        user: "Ella Mitchell",
        comment: "Perfect for yoga and meditation.",
        rating: 4.6,
        date: "May 10, 2023",
        avatar: require("../../assets/profiles/profile10.jpg"),
      },
      {
        user: "Leo Harris",
        comment: "The staff were incredibly friendly.",
        rating: 4.7,
        date: "Jun 21, 2023",
        avatar: require("../../assets/profiles/profile2.jpg"),
      },
      {
        user: "Lily Howard",
        comment: "A great place to relax and recharge.",
        rating: 4.8,
        date: "Jul 17, 2023",
        avatar: require("../../assets/profiles/profile8.jpg"),
      },
      {
        user: "Sophia Bennett",
        comment: "Perfect location for exploring NYC.",
        rating: 5,
        date: "Aug 5, 2023",
        avatar: require("../../assets/profiles/profile3.jpg"),
      },
      {
        user: "Mason Carter",
        comment: "The rooftop bar had amazing views.",
        rating: 4.9,
        date: "Sep 11, 2023",
        avatar: require("../../assets/profiles/profile1.jpg"),
      },
      {
        user: "Emma Kelly",
        comment: "Rooms were spacious and modern.",
        rating: 4.8,
        date: "Oct 3, 2023",
        avatar: require("../../assets/profiles/profile11.jpg"),
      },
      {
        user: "Liam Taylor",
        comment: "Great value for such a central location.",
        rating: 4.7,
        date: "Nov 12, 2023",
        avatar: require("../../assets/profiles/profile5.jpg"),
      },
      {
        user: "Olivia White",
        comment: "The breakfast buffet was excellent.",
        rating: 5,
        date: "Dec 15, 2023",
        avatar: require("../../assets/profiles/profile12.jpg"),
      },
    ],
    images: [
      require("../../assets/images/image4.jpg"),
      require("../../assets/images/image5.jpg"),
      require("../../assets/images/image7.jpg"),
      require("../../assets/images/image18.jpg"),
      require("../../assets/images/image23.jpg"),
      require("../../assets/images/image24.jpg"),
      require("../../assets/images/image3.jpg"),
    ],
  },
  {
    id: "5",
    name: "Lakefront Lodge",
    location: "Geneva, Switzerland",
    price: "250,000",
    rating: "4.9",
    description:
      "Escape to a picturesque lodge by the lake with stunning water views.",
    longAddress: "456 Lakefront Avenue, Geneva, Switzerland",
    facilities: [
      "lake view",
      "Restaurant",
      "boat",
      "breakfast",
      "wifi",
      "parking",
      "spa",
      "pet",
    ],
    reviews: [
      {
        user: "Sophia Martin",
        rating: 5,
        comment: "The lake view was breathtaking!",
        date: "Jan 12, 2023",
        avatar: require("../../assets/profiles/profile1.jpg"),
      },
      {
        user: "Jake Green",
        rating: 4.8,
        comment: "Fantastic place to relax and unwind.",
        date: "Feb 25, 2023",
        avatar: require("../../assets/profiles/profile2.jpg"),
      },
      {
        user: "Emma Hill",
        comment: "Best ski resort I’ve ever stayed at.",
        rating: 5,
        date: "Mar 8, 2023",
        avatar: require("../../assets/profiles/profile3.jpg"),
      },
      {
        user: "William Scott",
        comment: "The food was incredible.",
        rating: 4.8,
        date: "Apr 4, 2023",
        avatar: require("../../assets/profiles/profile4.jpg"),
      },
      {
        user: "James Brown",
        comment: "A luxurious alpine experience.",
        rating: 4.9,
        date: "May 18, 2023",
        avatar: require("../../assets/profiles/profile5.jpg"),
      },
      {
        user: "Ava Harris",
        comment: "The spa was perfect after a long day of skiing.",
        rating: 5,
        date: "Jun 1, 2023",
        avatar: require("../../assets/profiles/profile6.jpg"),
      },
      {
        user: "Oliver Taylor",
        comment: "Beautiful and tranquil.",
        rating: 4.8,
        date: "Jul 10, 2023",
        avatar: require("../../assets/profiles/profile7.jpg"),
      },
      {
        user: "Leo Martinez",
        comment: "Great cocktails by the beach.",
        rating: 4.5,
        date: "Aug 20, 2023",
        avatar: require("../../assets/profiles/profile8.jpg"),
      },
      {
        user: "Sophia Lopez",
        comment: "The bungalows were so charming.",
        rating: 4.4,
        date: "Sep 4, 2023",
        avatar: require("../../assets/profiles/profile9.jpg"),
      },
      {
        user: "Ava Young",
        comment: "Fantastic spot for water sports.",
        rating: 4.5,
        date: "Oct 15, 2023",
        avatar: require("../../assets/profiles/profile10.jpg"),
      },
    ],
    images: [
      require("../../assets/images/image9.jpg"),
      require("../../assets/images/image8.jpg"),
      require("../../assets/images/image7.jpg"),
      require("../../assets/images/image22.jpg"),
      require("../../assets/images/image16.jpg"),
      require("../../assets/images/image14.jpg"),
      require("../../assets/images/image17.jpg"),
    ],
  },
  {
    id: "6",
    name: "Jungle Retreat",
    location: "Bali, Indonesia",
    price: "110,000",
    rating: "4.4",
    description:
      "Immerse yourself in nature with our eco-friendly resort surrounded by greenery.",
    longAddress: "789 Jungle Road, Bali, Indonesia",
    facilities: [
      "parking",
      "yoga",
      "hot tub",
      "nature",
      "spa",
      "wifi",
      "pool",
      "restaurant",
      "bar",
      " mountain view",
      "breakfast",
    ],
    reviews: [
      {
        user: "Eva Brown",
        rating: 4.5,
        comment: "A peaceful escape into nature!",
        date: "Jan 5, 2023",
        avatar: require("../../assets/profiles/profile1.jpg"),
      },
      {
        user: "Tom Wilson",
        rating: 4.3,
        comment: "The yoga classes were amazing.",
        date: "Feb 14, 2023",
        avatar: require("../../assets/profiles/profile2.jpg"),
      },
      {
        user: "Emma Hill",
        comment: "Best ski resort I’ve ever stayed at.",
        rating: 5,
        date: "Mar 9, 2023",
        avatar: require("../../assets/profiles/profile3.jpg"),
      },
      {
        user: "William Scott",
        comment: "The food was incredible.",
        rating: 4.8,
        date: "Apr 17, 2023",
        avatar: require("../../assets/profiles/profile4.jpg"),
      },
      {
        user: "James Brown",
        comment: "A luxurious alpine experience.",
        rating: 4.9,
        date: "May 22, 2023",
        avatar: require("../../assets/profiles/profile5.jpg"),
      },
      {
        user: "Ava Harris",
        comment: "The spa was perfect after a long day of skiing.",
        rating: 5,
        date: "Jun 3, 2023",
        avatar: require("../../assets/profiles/profile6.jpg"),
      },
      {
        user: "Oliver Taylor",
        comment: "Beautiful and tranquil.",
        rating: 4.8,
        date: "Jul 11, 2023",
        avatar: require("../../assets/profiles/profile7.jpg"),
      },
      {
        user: "Ella Moore",
        comment: "Loved the beachfront yoga classes.",
        rating: 4.6,
        date: "Aug 8, 2023",
        avatar: require("../../assets/profiles/profile8.jpg"),
      },
      {
        user: "Mason Allen",
        comment: "Very relaxing atmosphere.",
        rating: 4.5,
        date: "Sep 5, 2023",
        avatar: require("../../assets/profiles/profile9.jpg"),
      },
      {
        user: "Jack Williams",
        comment: "Amazing views from every room.",
        rating: 5,
        date: "Oct 10, 2023",
        avatar: require("../../assets/profiles/profile10.jpg"),
      },
      {
        user: "Luna Collins",
        comment: "The fireplace was perfect for chilly evenings.",
        rating: 4.8,
        date: "Nov 12, 2023",
        avatar: require("../../assets/profiles/profile11.jpg"),
      },
    ],
    images: [
      require("../../assets/images/image17.jpg"),
      require("../../assets/images/image5.jpg"),
      require("../../assets/images/image23.jpg"),
      require("../../assets/images/image7.jpg"),
      require("../../assets/images/image2.jpg"),
      require("../../assets/images/image14.jpg"),
      require("../../assets/images/image15.jpg"),
      require("../../assets/images/image12.jpg"),
    ],
  },
  {
    id: "7",
    name: "Island Dreams Resort",
    location: "Maldives",
    price: "290,000",
    rating: "4.8",
    description:
      "Luxury villas above crystal-clear waters, offering the ultimate island escape.",
    longAddress: "101 Paradise Beach, Maldives",
    facilities: [
      "bar",
      "pool",
      "snorkeling",
      "all-inclusive",
      "spa",
      "wifi",
      "beach",
      "restaurant",
      "fireplace",
    ],
    reviews: [
      {
        user: "Laura Smith",
        rating: 5,
        comment: "Pure paradise on earth!",
        date: "Jan 15, 2023",
        avatar: require("../../assets/profiles/profile1.jpg"),
      },
      {
        user: "Chris Miller",
        rating: 4.9,
        comment: "The overwater villas were unforgettable.",
        date: "Feb 20, 2023",
        avatar: require("../../assets/profiles/profile2.jpg"),
      },
      {
        user: "Sophia Bennett",
        comment: "Perfect location for exploring NYC.",
        rating: 5,
        date: "Mar 25, 2023",
        avatar: require("../../assets/profiles/profile3.jpg"),
      },
      {
        user: "Mason Carter",
        comment: "The rooftop bar had amazing views.",
        rating: 4.9,
        date: "Apr 2, 2023",
        avatar: require("../../assets/profiles/profile4.jpg"),
      },
      {
        user: "Emma Kelly",
        comment: "Rooms were spacious and modern.",
        rating: 4.8,
        date: "May 6, 2023",
        avatar: require("../../assets/profiles/profile5.jpg"),
      },
      {
        user: "Liam Taylor",
        comment: "Great value for such a central location.",
        rating: 4.7,
        date: "Jun 15, 2023",
        avatar: require("../../assets/profiles/profile6.jpg"),
      },
      {
        user: "Olivia White",
        comment: "The breakfast buffet was excellent.",
        rating: 5,
        date: "Jul 20, 2023",
        avatar: require("../../assets/profiles/profile7.jpg"),
      },
    ],
    images: [
      require("../../assets/images/image8.jpg"),
      require("../../assets/images/image7.jpg"),
      require("../../assets/images/image5.jpg"),
      require("../../assets/images/image12.jpg"),
      require("../../assets/images/image19.jpg"),
    ],
  },
  {
    id: "8",
    name: "Countryside Inn",
    location: "Tuscany, Italy",
    price: "120,000",
    rating: "4.1",
    description:
      "Charming countryside inn with breathtaking vineyard views and Italian cuisine.",
    longAddress: "22 Vineyard Lane, Tuscany, Italy",
    facilities: [
      "pool",
      "breakfast",
      "fireplace",
      "cycling",
      "wifi",
      "restaurant",
      "bar",
      "parking",
    ],
    reviews: [
      {
        user: "Diana Evans",
        rating: 4.2,
        comment: "Perfect for wine lovers!",
        date: "Aug 1, 2023",
        avatar: require("../../assets/profiles/profile8.jpg"),
      },
      {
        user: "George White",
        rating: 4.1,
        comment: "Beautiful and peaceful location.",
        date: "Sep 10, 2023",
        avatar: require("../../assets/profiles/profile9.jpg"),
      },
      {
        user: "Amelia Ross",
        comment: "The spa treatments were incredible.",
        rating: 4.8,
        date: "Oct 3, 2023",
        avatar: require("../../assets/profiles/profile10.jpg"),
      },
      {
        user: "Ella Mitchell",
        comment: "Perfect for yoga and meditation.",
        rating: 4.6,
        date: "Nov 12, 2023",
        avatar: require("../../assets/profiles/profile11.jpg"),
      },
    ],
    images: [
      require("../../assets/images/image14.jpg"),
      require("../../assets/images/image9.jpg"),
      require("../../assets/images/image17.jpg"),
      require("../../assets/images/image1.jpg"),
      require("../../assets/images/image23.jpg"),
    ],
  },
  {
    id: "9",
    name: "Urban Comfort",
    location: "London, UK",
    price: "150,000",
    rating: "4.3",
    description:
      "A modern, urban hotel with sleek designs and easy access to city attractions.",
    longAddress: "11 Comfort Street, London, UK",
    facilities: ["wifi", "city view", "bar", "meeting", "gym"],
    reviews: [
      {
        user: "Olivia Brown",
        rating: 4.3,
        comment: "Convenient location and comfortable stay.",
        date: "Jan 15, 2023",
        avatar: require("../../assets/profiles/profile12.jpg"),
      },
      {
        user: "Ethan Lee",
        rating: 4.5,
        comment: "Loved the modern design!",
        date: "Feb 20, 2023",
        avatar: require("../../assets/profiles/profile13.jpg"),
      },
      {
        user: "David Clarke",
        comment: "The most luxurious stay I’ve ever had.",
        rating: 5,
        date: "Mar 5, 2023",
        avatar: require("../../assets/profiles/profile14.jpg"),
      },
      {
        user: "Samantha Yates",
        comment: "The poolside service was excellent.",
        rating: 4.9,
        date: "Apr 10, 2023",
        avatar: require("../../assets/profiles/profile15.jpg"),
      },
      {
        user: "Oliver King",
        comment: "A must-visit in Dubai.",
        rating: 5,
        date: "May 1, 2023",
        avatar: require("../../assets/profiles/profile16.jpg"),
      },
      {
        user: "Chloe Parker",
        comment: "Stunning views and exceptional rooms.",
        rating: 4.8,
        date: "Jun 12, 2023",
        avatar: require("../../assets/profiles/profile2.jpg"),
      },
      {
        user: "Ethan Lopez",
        comment: "Loved the Arabic-themed dining options.",
        rating: 5,
        date: "Jul 8, 2023",
        avatar: require("../../assets/profiles/profile3.jpg"),
      },
    ],
    images: [
      require("../../assets/images/image19.jpg"),
      require("../../assets/images/image20.jpg"),
      require("../../assets/images/image3.jpg"),
      require("../../assets/images/image5.jpg"),
      require("../../assets/images/image18.jpg"),
      require("../../assets/images/image15.jpg"),
    ],
  },
  {
    id: "10",
    name: "Coastal Bliss",
    location: "Sydney, Australia",
    price: "220,000",
    rating: "4.8",
    description:
      "Beachfront luxury with panoramic ocean views and exclusive amenities.",
    longAddress: "33 Beachside Avenue, Sydney, Australia",
    facilities: [
      "beach",
      "pool",
      "spa",
      "wifi",
      "meeting",
      "gym",
      "parking",
      "restaurant",
      "bar",
    ],
    reviews: [
      {
        user: "Alice Turner",
        rating: 5,
        comment: "The view was spectacular!",
        date: "Jan 22, 2023",
        avatar: require("../../assets/profiles/profile4.jpg"),
      },
      {
        user: "Jack Harris",
        rating: 4.7,
        comment: "Great for a romantic getaway.",
        date: "Feb 5, 2023",
        avatar: require("../../assets/profiles/profile5.jpg"),
      },
      {
        user: "Nina Patel",
        comment: "Amazing food and perfect sunsets.",
        rating: 4.9,
        date: "Mar 18, 2023",
        avatar: require("../../assets/profiles/profile6.jpg"),
      },
      {
        user: "Liam Carter",
        comment: "A little pricey, but worth every penny.",
        rating: 4.8,
        date: "Apr 2, 2023",
        avatar: require("../../assets/profiles/profile7.jpg"),
      },
      {
        user: "Ella Fitzgerald",
        comment: "Best snorkeling experience ever.",
        rating: 5,
        date: "May 6, 2023",
        avatar: require("../../assets/profiles/profile8.jpg"),
      },
      {
        user: "Emma Stone",
        comment: "Perfect for business trips.",
        rating: 4.5,
        date: "Jun 15, 2023",
        avatar: require("../../assets/profiles/profile9.jpg"),
      },
      {
        user: "Harry Brown",
        comment: "Loved the rooftop bar.",
        rating: 4.7,
        date: "Jul 20, 2023",
        avatar: require("../../assets/profiles/profile10.jpg"),
      },
      {
        user: "Sophia Li",
        comment: "The room design was modern and elegant.",
        rating: 4.6,
        date: "Aug 3, 2023",
        avatar: require("../../assets/profiles/profile11.jpg"),
      },
      {
        user: "Ben Carter",
        comment: "Great ski slopes and cozy fireplaces.",
        rating: 5,
        date: "Sep 9, 2023",
        avatar: require("../../assets/profiles/profile12.jpg"),
      },
      {
        user: "Emily Wong",
        comment: "A winter paradise with excellent staff.",
        rating: 4.9,
        date: "Oct 18, 2023",
        avatar: require("../../assets/profiles/profile13.jpg"),
      },
      {
        user: "Chris Brown",
        comment: "Loved the mulled wine by the fireplace.",
        rating: 4.8,
        date: "Nov 1, 2023",
        avatar: require("../../assets/profiles/profile14.jpg"),
      },
    ],
    images: [
      require("../../assets/images/image20.jpg"),
      require("../../assets/images/image15.jpg"),
      require("../../assets/images/image18.jpg"),
      require("../../assets/images/image14.jpg"),
      require("../../assets/images/image3.jpg"),
      require("../../assets/images/image2.jpg"),
      require("../../assets/images/image1.jpg"),
      require("../../assets/images/image16.jpg"),
    ],
  },
  {
    id: "11",
    name: "Coastal Retreat",
    location: "Santorini, Greece",
    longAddress: "123 Seaside Blvd, Santorini, Greece, 84700",
    price: "75,000",
    rating: "4.7",
    description:
      "A serene coastal retreat offering breathtaking ocean views and luxurious accommodations.",
    facilities: ["wifi", "restaurant", "pool", "spa", "gym", "beach", "bar"],
    images: [
      require("../../assets/images/image21.jpg"),
      require("../../assets/images/image19.jpg"),
      require("../../assets/images/image13.jpg"),
      require("../../assets/images/image4.jpg"),
      require("../../assets/images/image7.jpg"),
      require("../../assets/images/image9.jpg"),
      require("../../assets/images/image10.jpg"),
    ],
    reviews: [
      {
        user: "Anna Michaels",
        comment: "Loved the infinity pool and the view was stunning!",
        rating: 5,
        date: "Jan 12, 2024",
        avatar: require("../../assets/profiles/profile15.jpg"),
      },
      {
        user: "Tom Greene",
        comment: "Amazing food and great service.",
        rating: 4.8,
        date: "Feb 3, 2024",
        avatar: require("../../assets/profiles/profile16.jpg"),
      },
      {
        user: "Sophia Lee",
        comment: "Perfect for a romantic getaway.",
        rating: 5,
        date: "Mar 15, 2024",
        avatar: require("../../assets/profiles/profile1.jpg"),
      },
      {
        user: "John Doe",
        comment: "The gym was well-equipped, and the staff were very polite.",
        rating: 4.6,
        date: "Apr 2, 2024",
        avatar: require("../../assets/profiles/profile2.jpg"),
      },
      {
        user: "Maria Alvarez",
        comment: "The spa treatments were heavenly!",
        rating: 5,
        date: "May 8, 2024",
        avatar: require("../../assets/profiles/profile3.jpg"),
      },
      {
        user: "David Clarke",
        comment: "The most luxurious stay I’ve ever had.",
        rating: 5,
        date: "Jun 19, 2024",
        avatar: require("../../assets/profiles/profile4.jpg"),
      },
      {
        user: "Samantha Yates",
        comment: "The poolside service was excellent.",
        rating: 4.9,
        date: "Jul 21, 2024",
        avatar: require("../../assets/profiles/profile5.jpg"),
      },
      {
        user: "Oliver King",
        comment: "A must-visit in Dubai.",
        rating: 5,
        date: "Aug 13, 2024",
        avatar: require("../../assets/profiles/profile6.jpg"),
      },
      {
        user: "Chloe Parker",
        comment: "Stunning views and exceptional rooms.",
        rating: 4.8,
        date: "Sep 25, 2024",
        avatar: require("../../assets/profiles/profile7.jpg"),
      },
      {
        user: "Ethan Lopez",
        comment: "Loved the Arabic-themed dining options.",
        rating: 5,
        date: "Oct 9, 2024",
        avatar: require("../../assets/profiles/profile8.jpg"),
      },
    ],
  },
  {
    id: "12",
    name: "The pheels",
    location: "Ajah, Lagos",
    longAddress: "45 Alpine St, Ajah, Lagos, 81611",
    price: "120,000",
    rating: "4.9",
    description:
      "Nestled in the heart of the mountains, this haven offers both adventure and relaxation.",
    facilities: ["wifi", "restaurant", "bar", "ski", "fireplace"],
    images: [
      require("../../assets/images/image5.jpg"),
      require("../../assets/images/image6.jpg"),
      require("../../assets/images/image7.jpg"),
      require("../../assets/images/image18.jpg"),
      require("../../assets/images/image17.jpg"),
      require("../../assets/images/image11.jpg"),
    ],
    reviews: [
      {
        user: "Ben Carter",
        comment: "Great ski slopes and cozy fireplaces.",
        rating: "5",
        date: "Nov 1, 2024",
        avatar: require("../../assets/profiles/profile9.jpg"),
      },
      {
        user: "Emily Wong",
        comment: "A winter paradise with excellent staff.",
        rating: "4.9",
        date: "Nov 5, 2024",
        avatar: require("../../assets/profiles/profile10.jpg"),
      },
      {
        user: "Chris Brown",
        comment: "Loved the mulled wine by the fireplace.",
        rating: "4.8",
        date: "Nov 12, 2024",
        avatar: require("../../assets/profiles/profile11.jpg"),
      },
      {
        user: "Lisa Harper",
        comment: "The ski instructors were top-notch.",
        rating: "5",
        date: "Dec 1, 2024",
        avatar: require("../../assets/profiles/profile12.jpg"),
      },
      {
        user: "Jack Morgan",
        comment: "Beautiful views and amazing facilities.",
        rating: "4.7",
        date: "Dec 6, 2024",
        avatar: require("../../assets/profiles/profile13.jpg"),
      },
      {
        user: "James Hill",
        comment: "So peaceful, a real escape from the city.",
        rating: "4.7",
        date: "Dec 15, 2024",
        avatar: require("../../assets/profiles/profile14.jpg"),
      },
      {
        user: "Amelia Ross",
        comment: "The spa treatments were incredible.",
        rating: "4.8",
        date: "Dec 19, 2024",
        avatar: require("../../assets/profiles/profile15.jpg"),
      },
      {
        user: "Ella Mitchell",
        comment: "Perfect for yoga and meditation.",
        rating: "4.6",
        date: "Jan 3, 2025",
        avatar: require("../../assets/profiles/profile16.jpg"),
      },
      {
        user: "Leo Harris",
        comment: "The staff were incredibly friendly.",
        rating: "4.7",
        date: "Jan 10, 2025",
        avatar: require("../../assets/profiles/profile1.jpg"),
      },
      {
        user: "Lily Howard",
        comment: "A great place to relax and recharge.",
        rating: "4.8",
        date: "Jan 15, 2025",
        avatar: require("../../assets/profiles/profile2.jpg"),
      },
      {
        user: "Sophia Bennett",
        comment: "Perfect location for exploring NYC.",
        rating: "5",
        date: "Feb 1, 2025",
        avatar: require("../../assets/profiles/profile3.jpg"),
      },
      {
        user: "Mason Carter",
        comment: "The rooftop bar had amazing views.",
        rating: "4.9",
        date: "Feb 5, 2025",
        avatar: require("../../assets/profiles/profile4.jpg"),
      },
      {
        user: "Emma Kelly",
        comment: "Rooms were spacious and modern.",
        rating: "4.8",
        date: "Feb 10, 2025",
        avatar: require("../../assets/profiles/profile5.jpg"),
      },
      {
        user: "Liam Taylor",
        comment: "Great value for such a central location.",
        rating: "4.7",
        date: "Feb 15, 2025",
        avatar: require("../../assets/profiles/profile6.jpg"),
      },
      {
        user: "Olivia White",
        comment: "The breakfast buffet was excellent.",
        rating: "5",
        date: "Feb 20, 2025",
        avatar: require("../../assets/profiles/profile7.jpg"),
      },
    ],
  },
  {
    id: "13",
    name: "Estabeez",
    location: "Ikoyi, Lagos",
    longAddress: "56 Akihabara St, Ikoyi, Lagos, 101-002",
    price: "95,000",
    rating: "4.6",
    description:
      "Experience the bustling city life with a blend of modern luxury.",
    facilities: [
      "wifi",
      "restaurant",
      "bar",
      "gym",
      "parking",
      "meeting",
      "breakfast",
      "pool",
    ],
    images: [
      require("../../assets/images/image10.jpg"),
      require("../../assets/images/image2.jpg"),
      require("../../assets/images/image23.jpg"),
      require("../../assets/images/image3.jpg"),
      require("../../assets/images/image17.jpg"),
      require("../../assets/images/image18.jpg"),
    ],
    reviews: [
      {
        user: "Alice Kim",
        comment: "Loved the sushi at the in-house restaurant!",
        rating: "4.8",
        date: "Mar 1, 2025",
        avatar: require("../../assets/profiles/profile8.jpg"),
      },
      {
        user: "Mike Jacobs",
        comment: "Central location and great facilities.",
        rating: "4.6",
        date: "Mar 3, 2025",
        avatar: require("../../assets/profiles/profile9.jpg"),
      },
      {
        user: "Emma Stone",
        comment: "Perfect for business trips.",
        rating: "4.5",
        date: "Mar 5, 2025",
        avatar: require("../../assets/profiles/profile10.jpg"),
      },
      {
        user: "Harry Brown",
        comment: "Loved the rooftop bar.",
        rating: "4.7",
        date: "Mar 7, 2025",
        avatar: require("../../assets/profiles/profile11.jpg"),
      },
      {
        user: "Sophia Li",
        comment: "The room design was modern and elegant.",
        rating: "4.6",
        date: "Mar 10, 2025",
        avatar: require("../../assets/profiles/profile12.jpg"),
      },
    ],
  },
  {
    id: "14",
    name: "Saragoza",
    location: "Pukhet, Tailand",
    longAddress: "12 Lagoon Rd, Pukhet, Tailand, 20252",
    price: "180,000",
    rating: "4.8",
    description: "Relax in a private villa surrounded by crystal-clear waters.",
    facilities: [
      "wifi",
      "pool",
      "bar",
      "spa",
      "beach",
      "restaurant",
      "parking",
    ],
    images: [
      require("../../assets/images/image14.jpg"),
      require("../../assets/images/image5.jpg"),
      require("../../assets/images/image6.jpg"),
      require("../../assets/images/image17.jpg"),
      require("../../assets/images/image18.jpg"),
      require("../../assets/images/image20.jpg"),
      require("../../assets/images/image1.jpg"),
      require("../../assets/images/image9.jpg"),
    ],
    reviews: [
      {
        user: "Alex Rivera",
        comment: "The private beach was a dream come true.",
        rating: "5",
        date: "Mar 1, 2025",
        avatar: require("../../assets/profiles/profile1.jpg"),
      },
      {
        user: "Nina Patel",
        comment: "Amazing food and perfect sunsets.",
        rating: "4.9",
        date: "Mar 3, 2025",
        avatar: require("../../assets/profiles/profile7.jpg"),
      },
      {
        user: "Liam Carter",
        comment: "A little pricey, but worth every penny.",
        rating: "4.8",
        date: "Mar 5, 2025",
        avatar: require("../../assets/profiles/profile3.jpg"),
      },
      {
        user: "Ella Fitzgerald",
        comment: "Best snorkeling experience ever.",
        rating: "5",
        date: "Mar 7, 2025",
        avatar: require("../../assets/profiles/profile9.jpg"),
      },
      {
        user: "Ryan Adams",
        comment: "The staff were very accommodating.",
        rating: "4.7",
        date: "Mar 10, 2025",
        avatar: require("../../assets/profiles/profile5.jpg"),
      },
      {
        user: "Leo Martinez",
        comment: "Great cocktails by the beach.",
        rating: "4.5",
        date: "Mar 12, 2025",
        avatar: require("../../assets/profiles/profile11.jpg"),
      },
      {
        user: "Sophia Lopez",
        comment: "The bungalows were so charming.",
        rating: "4.4",
        date: "Mar 14, 2025",
        avatar: require("../../assets/profiles/profile2.jpg"),
      },
      {
        user: "Ava Young",
        comment: "Fantastic spot for water sports.",
        rating: "4.5",
        date: "Mar 16, 2025",
        avatar: require("../../assets/profiles/profile8.jpg"),
      },
      {
        user: "Ella Moore",
        comment: "Loved the beachfront yoga classes.",
        rating: "4.6",
        date: "Mar 18, 2025",
        avatar: require("../../assets/profiles/profile6.jpg"),
      },
      {
        user: "Mason Allen",
        comment: "Very relaxing atmosphere.",
        rating: "4.5",
        date: "Mar 20, 2025",
        avatar: require("../../assets/profiles/profile10.jpg"),
      },
    ],
  },
  {
    id: "15",
    name: "Golden Sands Resort",
    location: "Dubai, UAE",
    longAddress: "33 Sheikh Zayed Rd, Dubai, UAE, 00000",
    price: "205,000",
    rating: "4.9",
    description:
      "A luxurious desert oasis with stunning architecture and top-tier services.",
    facilities: ["wifi", "restaurant", "pool", "spa", "gym"],
    images: [
      require("../../assets/images/image19.jpg"),
      require("../../assets/images/image20.jpg"),
      require("../../assets/images/image22.jpg"),
      require("../../assets/images/image2.jpg"),
      require("../../assets/images/image3.jpg"),
      require("../../assets/images/image10.jpg"),
    ],
    reviews: [
      {
        user: "David Clarke",
        comment: "The most luxurious stay I’ve ever had.",
        rating: "5",
        date: "Jan 1, 2025",
        avatar: require("../../assets/profiles/profile1.jpg"),
      },
      {
        user: "Samantha Yates",
        comment: "The poolside service was excellent.",
        rating: "4.9",
        date: "Jan 3, 2025",
        avatar: require("../../assets/profiles/profile8.jpg"),
      },
      {
        user: "Oliver King",
        comment: "A must-visit in Dubai.",
        rating: "5",
        date: "Jan 5, 2025",
        avatar: require("../../assets/profiles/profile3.jpg"),
      },
      {
        user: "Chloe Parker",
        comment: "Stunning views and exceptional rooms.",
        rating: "4.8",
        date: "Jan 7, 2025",
        avatar: require("../../assets/profiles/profile7.jpg"),
      },
      {
        user: "Ethan Lopez",
        comment: "Loved the Arabic-themed dining options.",
        rating: "5",
        date: "Jan 9, 2025",
        avatar: require("../../assets/profiles/profile6.jpg"),
      },
      {
        user: "Alex Rivera",
        comment: "The private beach was a dream come true.",
        rating: "5",
        date: "Jan 11, 2025",
        avatar: require("../../assets/profiles/profile5.jpg"),
      },
      {
        user: "Nina Patel",
        comment: "Amazing food and perfect sunsets.",
        rating: "4.9",
        date: "Jan 13, 2025",
        avatar: require("../../assets/profiles/profile2.jpg"),
      },
      {
        user: "Liam Carter",
        comment: "A little pricey, but worth every penny.",
        rating: "4.8",
        date: "Jan 15, 2025",
        avatar: require("../../assets/profiles/profile9.jpg"),
      },
      {
        user: "Ella Fitzgerald",
        comment: "Best snorkeling experience ever.",
        rating: "5",
        date: "Jan 17, 2025",
        avatar: require("../../assets/profiles/profile4.jpg"),
      },
      {
        user: "Ryan Adams",
        comment: "The staff were very accommodating.",
        rating: "4.7",
        date: "Jan 19, 2025",
        avatar: require("../../assets/profiles/profile10.jpg"),
      },
    ],
  },
  {
    id: "16",
    name: "Rainforest Retreat",
    location: "Bali, Indonesia",
    longAddress: "45 Jungle Path, Ubud, Bali, 80571",
    price: "70,000",
    rating: "4.6",
    description:
      "Reconnect with nature in this peaceful retreat surrounded by lush greenery.",
    facilities: [
      "wifi",
      "restaurant",
      "bar",
      "pool",
      "spa",
      "yoga",
      "nature",
      "parking",
    ],
    images: [
      require("../../assets/images/image1.jpg"),
      require("../../assets/images/image2.jpg"),
      require("../../assets/images/image13.jpg"),
      require("../../assets/images/image24.jpg"),
      require("../../assets/images/image8.jpg"),
      require("../../assets/images/image12.jpg"),
      require("../../assets/images/image11.jpg"),
    ],
    reviews: [
      {
        user: "James Hill",
        comment: "So peaceful, a real escape from the city.",
        rating: "4.7",
        date: "Jan 1, 2025",
        avatar: require("../../assets/profiles/profile11.jpg"),
      },
      {
        user: "Amelia Ross",
        comment: "The spa treatments were incredible.",
        rating: "4.8",
        date: "Jan 3, 2025",
        avatar: require("../../assets/profiles/profile12.jpg"),
      },
      {
        user: "Ella Mitchell",
        comment: "Perfect for yoga and meditation.",
        rating: "4.6",
        date: "Jan 5, 2025",
        avatar: require("../../assets/profiles/profile13.jpg"),
      },
      {
        user: "Leo Harris",
        comment: "The staff were incredibly friendly.",
        rating: "4.7",
        date: "Jan 7, 2025",
        avatar: require("../../assets/profiles/profile14.jpg"),
      },
      {
        user: "Lily Howard",
        comment: "A great place to relax and recharge.",
        rating: "4.8",
        date: "Jan 9, 2025",
        avatar: require("../../assets/profiles/profile15.jpg"),
      },
      {
        user: "Alex Rivera",
        comment: "The private beach was a dream come true.",
        rating: "5",
        date: "Jan 11, 2025",
        avatar: require("../../assets/profiles/profile5.jpg"),
      },
      {
        user: "Nina Patel",
        comment: "Amazing food and perfect sunsets.",
        rating: "4.9",
        date: "Jan 13, 2025",
        avatar: require("../../assets/profiles/profile2.jpg"),
      },
      {
        user: "Liam Carter",
        comment: "A little pricey, but worth every penny.",
        rating: "4.8",
        date: "Jan 15, 2025",
        avatar: require("../../assets/profiles/profile9.jpg"),
      },
      {
        user: "Ella Fitzgerald",
        comment: "Best snorkeling experience ever.",
        rating: "5",
        date: "Jan 17, 2025",
        avatar: require("../../assets/profiles/profile4.jpg"),
      },
      {
        user: "Ryan Adams",
        comment: "The staff were very accommodating.",
        rating: "4.7",
        date: "Jan 19, 2025",
        avatar: require("../../assets/profiles/profile10.jpg"),
      },
      {
        user: "Alice Kim",
        comment: "Loved the sushi at the in-house restaurant!",
        rating: "4.8",
        date: "Jan 21, 2025",
        avatar: require("../../assets/profiles/profile3.jpg"),
      },
      {
        user: "Mike Jacobs",
        comment: "Central location and great facilities.",
        rating: "4.6",
        date: "Jan 23, 2025",
        avatar: require("../../assets/profiles/profile16.jpg"),
      },
      {
        user: "Emma Stone",
        comment: "Perfect for business trips.",
        rating: "4.5",
        date: "Jan 25, 2025",
        avatar: require("../../assets/profiles/profile7.jpg"),
      },
      {
        user: "Harry Brown",
        comment: "Loved the rooftop bar.",
        rating: "4.7",
        date: "Jan 27, 2025",
        avatar: require("../../assets/profiles/profile8.jpg"),
      },
      {
        user: "Sophia Li",
        comment: "The room design was modern and elegant.",
        rating: "4.6",
        date: "Jan 29, 2025",
        avatar: require("../../assets/profiles/profile6.jpg"),
      },
    ],
  },
  {
    id: "17",
    name: "Cityscape Hotel",
    location: "New York, USA",
    longAddress: "100 Manhattan Ave, New York, NY, 10001",
    price: "150,000",
    rating: "4.8",
    description: "A modern city escape located in the heart of Manhattan.",
    facilities: ["wifi", "restaurant", "gym", "bar", "parking", "city view"],
    images: [
      require("../../assets/images/image5.jpg"),
      require("../../assets/images/image2.jpg"),
      require("../../assets/images/image17.jpg"),
      require("../../assets/images/image18.jpg"),
      require("../../assets/images/image1.jpg"),
      require("../../assets/images/image3.jpg"),
      require("../../assets/images/image20.jpg"),
    ],
    reviews: [
      {
        user: "Sophia Bennett",
        comment: "Perfect location for exploring NYC.",
        rating: "5",
        date: "Feb 1, 2025",
        avatar: require("../../assets/profiles/profile1.jpg"),
      },
      {
        user: "Mason Carter",
        comment: "The rooftop bar had amazing views.",
        rating: "4.9",
        date: "Feb 3, 2025",
        avatar: require("../../assets/profiles/profile2.jpg"),
      },
      {
        user: "Emma Kelly",
        comment: "Rooms were spacious and modern.",
        rating: "4.8",
        date: "Feb 5, 2025",
        avatar: require("../../assets/profiles/profile3.jpg"),
      },
      {
        user: "Liam Taylor",
        comment: "Great value for such a central location.",
        rating: "4.7",
        date: "Feb 7, 2025",
        avatar: require("../../assets/profiles/profile4.jpg"),
      },
      {
        user: "Olivia White",
        comment: "The breakfast buffet was excellent.",
        rating: "5",
        date: "Feb 9, 2025",
        avatar: require("../../assets/profiles/profile5.jpg"),
      },
    ],
  },
  {
    id: "18",
    name: "Lakeview Lodge",
    location: "Queenstown, New Zealand",
    longAddress: "88 Scenic Rd, Queenstown, New Zealand, 9300",
    price: "112,000",
    rating: "4.7",
    description:
      "Enjoy breathtaking views of the lake and surrounding mountains.",
    facilities: [
      "wifi",
      "restaurant",
      "pool",
      "gym",
      "fireplace",
      "parking",
      "spa",
      "lake",
    ],
    images: [
      require("../../assets/images/image9.jpg"),
      require("../../assets/images/image13.jpg"),
      require("../../assets/images/image10.jpg"),
      require("../../assets/images/image2.jpg"),
      require("../../assets/images/image21.jpg"),
      require("../../assets/images/image20.jpg"),
      require("../../assets/images/image14.jpg"),
    ],
    reviews: [
      {
        user: "Alice Kim",
        comment: "Loved the sushi at the in-house restaurant!",
        rating: "4.8",
        date: "Jan 1, 2025",
        avatar: require("../../assets/profiles/profile6.jpg"),
      },
      {
        user: "Mike Jacobs",
        comment: "Central location and great facilities.",
        rating: "4.6",
        date: "Jan 3, 2025",
        avatar: require("../../assets/profiles/profile7.jpg"),
      },
      {
        user: "Emma Stone",
        comment: "Perfect for business trips.",
        rating: "4.5",
        date: "Jan 5, 2025",
        avatar: require("../../assets/profiles/profile8.jpg"),
      },
      {
        user: "Harry Brown",
        comment: "Loved the rooftop bar.",
        rating: "4.7",
        date: "Jan 7, 2025",
        avatar: require("../../assets/profiles/profile9.jpg"),
      },
      {
        user: "Sophia Li",
        comment: "The room design was modern and elegant.",
        rating: "4.6",
        date: "Jan 9, 2025",
        avatar: require("../../assets/profiles/profile10.jpg"),
      },
      {
        user: "Jack Williams",
        comment: "Amazing views from every room.",
        rating: "5",
        date: "Jan 11, 2025",
        avatar: require("../../assets/profiles/profile11.jpg"),
      },
      {
        user: "Luna Collins",
        comment: "The fireplace was perfect for chilly evenings.",
        rating: "4.8",
        date: "Jan 13, 2025",
        avatar: require("../../assets/profiles/profile12.jpg"),
      },
      {
        user: "Ben Carter",
        comment: "Great ski slopes and cozy fireplaces.",
        rating: "5",
        date: "Jan 15, 2025",
        avatar: require("../../assets/profiles/profile13.jpg"),
      },
      {
        user: "Emily Wong",
        comment: "A winter paradise with excellent staff.",
        rating: "4.9",
        date: "Jan 17, 2025",
        avatar: require("../../assets/profiles/profile14.jpg"),
      },
      {
        user: "Oscar Davis",
        comment: "The staff went above and beyond.",
        rating: "4.7",
        date: "Jan 19, 2025",
        avatar: require("../../assets/profiles/profile15.jpg"),
      },
      {
        user: "Mia Hall",
        comment: "Great location for skiing.",
        rating: "4.9",
        date: "Jan 21, 2025",
        avatar: require("../../assets/profiles/profile16.jpg"),
      },
      {
        user: "Ella Wilson",
        comment: "Comfortable and cozy rooms.",
        rating: "4.6",
        date: "Jan 23, 2025",
        avatar: require("../../assets/profiles/profile1.jpg"),
      },
    ],
  },
  {
    id: "19",
    name: "Beachside Bungalows",
    location: "Cancun, Mexico",
    longAddress: "22 Ocean Rd, Cancun, Mexico, 77500",
    price: "65,000",
    rating: "4.5",
    description: "Relax in beachfront bungalows with a laid-back vibe.",
    facilities: [
      "wifi",
      "bar",
      "pool",
      "beach",
      "restaurant",
      "spa",
      "parking",
    ],
    images: [
      require("../../assets/images/image13.jpg"),
      require("../../assets/images/image1.jpg"),
      require("../../assets/images/image5.jpg"),
      require("../../assets/images/image16.jpg"),
      require("../../assets/images/image14.jpg"),
      require("../../assets/images/image9.jpg"),
      require("../../assets/images/image10.jpg"),
    ],
    reviews: [
      {
        user: "Leo Martinez",
        comment: "Great cocktails by the beach.",
        rating: "4.5",
        date: "Jan 1, 2025",
        avatar: require("../../assets/profiles/profile2.jpg"),
      },
      {
        user: "Sophia Lopez",
        comment: "The bungalows were so charming.",
        rating: "4.4",
        date: "Jan 3, 2025",
        avatar: require("../../assets/profiles/profile3.jpg"),
      },
      {
        user: "Ava Young",
        comment: "Fantastic spot for water sports.",
        rating: "4.5",
        date: "Jan 5, 2025",
        avatar: require("../../assets/profiles/profile4.jpg"),
      },
      {
        user: "Chris Brown",
        comment: "Loved the mulled wine by the fireplace.",
        rating: "4.8",
        date: "Jan 7, 2025",
        avatar: require("../../assets/profiles/profile5.jpg"),
      },
      {
        user: "Lisa Harper",
        comment: "The ski instructors were top-notch.",
        rating: "5",
        date: "Jan 9, 2025",
        avatar: require("../../assets/profiles/profile6.jpg"),
      },
      {
        user: "Jack Morgan",
        comment: "Beautiful views and amazing facilities.",
        rating: "4.7",
        date: "Jan 11, 2025",
        avatar: require("../../assets/profiles/profile7.jpg"),
      },
      {
        user: "Mike Jacobs",
        comment: "Central location and great facilities.",
        rating: "4.6",
        date: "Jan 13, 2025",
        avatar: require("../../assets/profiles/profile8.jpg"),
      },
      {
        user: "Emma Stone",
        comment: "Perfect for business trips.",
        rating: "4.5",
        date: "Jan 15, 2025",
        avatar: require("../../assets/profiles/profile9.jpg"),
      },
      {
        user: "Harry Brown",
        comment: "Loved the rooftop bar.",
        rating: "4.7",
        date: "Jan 17, 2025",
        avatar: require("../../assets/profiles/profile10.jpg"),
      },
      {
        user: "Ella Moore",
        comment: "Loved the beachfront yoga classes.",
        rating: "4.6",
        date: "Jan 19, 2025",
        avatar: require("../../assets/profiles/profile11.jpg"),
      },
      {
        user: "Mason Allen",
        comment: "Very relaxing atmosphere.",
        rating: "4.5",
        date: "Jan 21, 2025",
        avatar: require("../../assets/profiles/profile12.jpg"),
      },
    ],
  },
  {
    id: "20",
    name: "Winter Wonderland Resort",
    location: "Zermatt, Switzerland",
    longAddress: "1 Glacier Rd, Zermatt, Switzerland, 3920",
    price: "253,000",
    rating: "4.9",
    description:
      "Experience the magic of the Swiss Alps with world-class skiing.",
    facilities: [
      "wifi",
      "restaurant",
      "bar",
      "ski",
      "spa",
      "fireplace",
      "parking",
      "mountain view",
      "breakfast",
    ],
    images: [
      require("../../assets/images/image7.jpg"),
      require("../../assets/images/image8.jpg"),
      require("../../assets/images/image19.jpg"),
      require("../../assets/images/image10.jpg"),
      require("../../assets/images/image11.jpg"),
      require("../../assets/images/image22.jpg"),
      require("../../assets/images/image18.jpg"),
      require("../../assets/images/image1.jpg"),
    ],
    reviews: [
      {
        user: "Emma Hill",
        comment: "Best ski resort I’ve ever stayed at.",
        rating: "5",
        date: "Jan 1, 2025",
        avatar: require("../../assets/profiles/profile1.jpg"),
      },
      {
        user: "William Scott",
        comment: "The food was incredible.",
        rating: "4.8",
        date: "Jan 3, 2025",
        avatar: require("../../assets/profiles/profile2.jpg"),
      },
      {
        user: "Anna Michaels",
        comment: "Loved the infinity pool and the view was stunning!",
        rating: "5",
        date: "Jan 5, 2025",
        avatar: require("../../assets/profiles/profile3.jpg"),
      },
      {
        user: "Tom Greene",
        comment: "Amazing food and great service.",
        rating: "4.8",
        date: "Jan 7, 2025",
        avatar: require("../../assets/profiles/profile4.jpg"),
      },
      {
        user: "Sophia Lee",
        comment: "Perfect for a romantic getaway.",
        rating: "5",
        date: "Jan 9, 2025",
        avatar: require("../../assets/profiles/profile5.jpg"),
      },
      {
        user: "John Doe",
        comment: "The gym was well-equipped, and the staff were very polite.",
        rating: "4.6",
        date: "Jan 11, 2025",
        avatar: require("../../assets/profiles/profile6.jpg"),
      },
      {
        user: "James Brown",
        comment: "A luxurious alpine experience.",
        rating: "4.9",
        date: "Jan 13, 2025",
        avatar: require("../../assets/profiles/profile7.jpg"),
      },
      {
        user: "Ava Harris",
        comment: "The spa was perfect after a long day of skiing.",
        rating: "5",
        date: "Jan 15, 2025",
        avatar: require("../../assets/profiles/profile8.jpg"),
      },
      {
        user: "Oliver Taylor",
        comment: "Beautiful and tranquil.",
        rating: "4.8",
        date: "Jan 17, 2025",
        avatar: require("../../assets/profiles/profile9.jpg"),
      },
    ],
  },
];

const slidesData = [
  {
    image: require("../../assets/images/image1.jpg"),
    textLines: [
      { text: "Last-minute", style: "sliderTextSemibold" },
      { text: "weekend", style: "sliderTextbold" },
      { text: "deals", style: "sliderText" },
    ],
  },
  {
    image: require("../../assets/images/image8.jpg"),
    textLines: [
      { text: "Get", style: "sliderTextSemibold" },
      { text: "10% OFF", style: "sliderTextbold" },
      { text: "on your first booking", style: "sliderText" },
    ],
  },
  {
    image: require("../../assets/images/image5.jpg"),
    textLines: [
      { text: "Planning", style: "sliderTextSemibold" },
      { text: "a new Escape?", style: "sliderTextbold" },
      { text: "Let's explore", style: "sliderText" },
    ],
  },
];

export { slidesData, hotels };
